name: Build Frontend Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/brunoagst/finance-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login no GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }} \
            --build-arg VITE_APP_URL=${{ vars.VITE_APP_URL }} \
            --build-arg VITE_KEYCLOAK_URL=${{ vars.VITE_KEYCLOAK_URL }} \
            --build-arg VITE_KEYCLOAK_REALM=${{ vars.VITE_KEYCLOAK_REALM }} \
            --build-arg VITE_KEYCLOAK_CLIENT_ID=${{ vars.VITE_KEYCLOAK_CLIENT_ID }} \
            -t $IMAGE_NAME:latest .

      - name: Push da imagem
        run: docker push $IMAGE_NAME:latest